[[wget2]]
arch = "aarch64"
git-tree-sha1 = "7ccdf9311d0f04189ec1f3032a338cdcd7ebb463"
os = "macos"

    [[wget2.download]]
    sha256 = "4a3829563d5b245fac82badefdfd33eee6537056606ac8d7bedc1569c7319fd3"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.aarch64-apple-darwin.tar.gz"
[[wget2]]
arch = "aarch64"
git-tree-sha1 = "01d80870a94a876011979f27250ba318fe8472fd"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "b6a81c0fe216113a1ab1efa5c7ebd50e11ad15f86cfa729c5216989e0ea0de13"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.aarch64-linux-gnu.tar.gz"
[[wget2]]
arch = "aarch64"
git-tree-sha1 = "4cb7737ab72956308d397a453ad5a338e880d214"
libc = "musl"
os = "linux"

    [[wget2.download]]
    sha256 = "6d7a8c27ec9a9bcba9f2f32b5fd62d05253795ace055241e6d99b62b798b4d01"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.aarch64-linux-musl.tar.gz"
[[wget2]]
arch = "aarch64"
git-tree-sha1 = "d50d25df932386def652883c1a2ae88be67fd6d2"
os = "freebsd"

    [[wget2.download]]
    sha256 = "c9c116041b2b7b891b564be006b90d8bf9f2a5f5f1ef8534237c322b71064780"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.aarch64-unknown-freebsd.tar.gz"
[[wget2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6355aa00c16ae425051cbde548370da20a952054"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "22cc9f706be442f60a700d925323224c1ebf994a7d09c5d352ecfae68350e245"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.armv6l-linux-gnueabihf.tar.gz"
[[wget2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "89a1da1fa4e9b1b4a9af2c1d887b7a35b633c6a7"
libc = "musl"
os = "linux"

    [[wget2.download]]
    sha256 = "aa04e6cb743573f4f64d1a9a3bb108d9e34daef1d70d2f23018de5f595bad238"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.armv6l-linux-musleabihf.tar.gz"
[[wget2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0cde8cf59ecdf78b240f7b3aa2045def9bda2407"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "8d973add12e5773e2f5714ff2081130ee2c1c54557cb7128d05ce5867039be4d"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.armv7l-linux-gnueabihf.tar.gz"
[[wget2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c1b02313793f7388b8577ec355ef68cb178465fd"
libc = "musl"
os = "linux"

    [[wget2.download]]
    sha256 = "e8456b5ce3e428e20789ca170073244982474713ce83b3452eb95936bf162382"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.armv7l-linux-musleabihf.tar.gz"
[[wget2]]
arch = "i686"
git-tree-sha1 = "bd61cc3d4b222a1606f0fb4856be76da05831910"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "0921ed93ad379858cd65d4bb2cd6f2bb68be1381f13d71f665cad2dad6294da2"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.i686-linux-gnu.tar.gz"
[[wget2]]
arch = "i686"
git-tree-sha1 = "132c7794b7286ee726e9d03e6450660c36feb09a"
libc = "musl"
os = "linux"

    [[wget2.download]]
    sha256 = "0f1d7b812988f0963f24c3c422869b9cf1f1a2f88ba16f8a4b0aaad10e4564c8"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.i686-linux-musl.tar.gz"
[[wget2]]
arch = "i686"
git-tree-sha1 = "ce718b51b678b80f915fcb8a558b8f23f31e99ca"
os = "windows"

    [[wget2.download]]
    sha256 = "9f7d0ac69f586df988d1d1e1a501d3d513021c1c3e84b932e49ebe6cf8a0066e"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.i686-w64-mingw32.tar.gz"
[[wget2]]
arch = "powerpc64le"
git-tree-sha1 = "6de4698031a9a3184d0cb77a9891e2af9c6ab275"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "742ad5981e3790a2a73840c086e160927f14c3a8a06b916c6abcff4ccd46e358"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.powerpc64le-linux-gnu.tar.gz"
[[wget2]]
arch = "riscv64"
git-tree-sha1 = "8c50558a8060323294b5c9939843288c670d0f22"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "ee285e1532d4a1dbf1293fc887b37606fd20e0491f83fe7b91ab84be7d9d1720"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.riscv64-linux-gnu.tar.gz"
[[wget2]]
arch = "x86_64"
git-tree-sha1 = "caa4625c1aa6815c9ccc64a95c7dfc60b65bbc8e"
os = "macos"

    [[wget2.download]]
    sha256 = "7a03413aa2216e90c84a4e9d506a7ce8d1f3fc6da74ceb045b562a36174a2ba5"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.x86_64-apple-darwin.tar.gz"
[[wget2]]
arch = "x86_64"
git-tree-sha1 = "3dcaf26c28e6a3c1377df6a6e64d00aa199b4dc2"
libc = "glibc"
os = "linux"

    [[wget2.download]]
    sha256 = "844f563a5d2052b6fda17b295e51ae60d81823ba84b6f89f54a0446c77a3bbfa"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.x86_64-linux-gnu.tar.gz"
[[wget2]]
arch = "x86_64"
git-tree-sha1 = "bd9275e98db8883488f2414336e29c67fccd2a30"
libc = "musl"
os = "linux"

    [[wget2.download]]
    sha256 = "6f42cfe3f7d34012fbc001f41f5a0861285b7a981d55085e8d45f1a8c0474c7c"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.x86_64-linux-musl.tar.gz"
[[wget2]]
arch = "x86_64"
git-tree-sha1 = "21997d7370e8bb8d228d33d8afb7baf4c85d5a1a"
os = "freebsd"

    [[wget2.download]]
    sha256 = "9080331b6fb6693800ca4f884017c0929e91c34e72551736481e04c160de1b01"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.x86_64-unknown-freebsd.tar.gz"
[[wget2]]
arch = "x86_64"
git-tree-sha1 = "af99cdfb07f4981d889bfa827c1788a83af2cb74"
os = "windows"

    [[wget2.download]]
    sha256 = "d04287f437536ea970542a8edbf72a772444ced2bfca2af4c28c0e12814cf1dd"
    url = "https://github.com/JuliaBinaryWrappers/wget2_jll.jl/releases/download/wget2-v2.2.1+0/wget2.v2.2.1.x86_64-w64-mingw32.tar.gz"
